Repository YCP-Swarm-Robotics-Capstone-2020-2021/melon, pull requests merged in 2021-03, with the labels that each got.

#3 feature/server
  CMakeLists.txt
  src/command_handler.cpp
  src/command_handler.h
  src/logger.cpp
  src/logger.h
  src/server.cpp
  src/state.pb.cc
  src/state.pb.h
  src/state.proto
  src/state_variables.h
Labels: enhancement

#7 add collector target system
  src/cmdhandler/command_handler.cpp
  src/cmdhandler/command_handler.h
  src/cmdhandler/state.proto
  src/cmdhandler/statevariables.h
Labels: enhancement

#13 feature/listableStates
  CMakeLists.txt
  src/cmdhandler/command_handler.cpp
  src/cmdhandler/command_handler.h
  src/main.cpp
Labels: enhancement

#16 cmd handler doc
  src/cmdhandler/command_handler.cpp
  src/cmdhandler/command_handler.h
  src/cmdhandler/server.cpp
  src/cmdhandler/session.cpp
  src/cmdhandler/session.h
Labels: documentation

#19 feature/cameraSystem
  src/cmdhandler/command_handler.cpp
  src/cmdhandler/command_handler.h
  src/cmdhandler/state.proto
  src/cmdhandler/statevariables.h
  src/collectorserver/collectorserver.cpp
Labels: enhancement

#23 fix loading a state with empty matrices
  src/cmdhandler/command_handler.cpp
Labels: bug

#27 refactor/stateProto
  src/cmdhandler/command_handler.cpp
  src/cmdhandler/state.proto
Labels: refactor

#31 Fix CMakeLists.txt so it works on non-windows
  CMakeLists.txt
  README.md
Labels: bug

#32 refactor/cmdConstants
  src/cmdhandler/command_handler.cpp
  src/cmdhandler/constants/commands.h
  src/cmdhandler/constants/systems.h
  src/cmdhandler/constants/variables.h
Labels: refactor
