Repository YCP-Swarm-Robotics-Capstone-2020-2021/melon, pull requests merged in 2021-04, with the labels that each got.

#40 Add condition variables
  src/cmdhandler/command_handler.cpp
  src/cmdhandler/globalstate.cpp
  src/cmdhandler/globalstate.h
  src/cmdhandler/statevariables.h
  src/main.cpp
Labels: enhancement

#47 Bug/camera init
  src/camera/abstractcamera.cpp
  src/camera/abstractcamera.h
  src/camera/camerawrapper.cpp
  src/main.cpp
Labels: bug

#49 Add support for opencv device id connections
  src/camera/opencvcamera.cpp
Labels: enhancement

#50 Rename camera url to camera source
  src/camera/abstractcamera.cpp
  src/camera/abstractcamera.h
  src/camera/opencvcamera.cpp
  src/camera/spinnakercamera.cpp
  src/cmdhandler/command_handler.cpp
  src/cmdhandler/constants/variables.h
  src/cmdhandler/state.proto
  src/cmdhandler/statevariables.h
  src/main.cpp
Labels: refactor

#52 feature/cmdHandlerTest
  CMakeLists.txt
  README.md
  tests/cmdhandler/camera_system_tests.cc
  tests/cmdhandler/collector_system_tests.cc
  tests/cmdhandler/command_handler_tests.cc
  tests/cmdhandler/robot_system_tets.cc
  tests/cmdhandler/state_system_tests.cc
Labels: enhancement, testing
